### ISSUE TITLE
could not use an html tag around Arabic character

### ISSUE THREAD

**Issue by inDiscover** [w3c/i18n-drafts#112]
Below is my code written in coldfusion. This code I am using inside PDF generation code. Here I want to concatenate name , amount and unit by using a single space and then i want to highlight the name part. But whenever I try to highlight the name (making bold , using span tag around the name) the Arabic words(name/amount/unit) are getting shuffled/rearranged. 

`<span style="font-weight: bold;color:black">#name#</span>#amount# #unit# `.

Below is the code to generate PDF in coldfusion.

```
<cfdocument filename="c:\arr-bill.pdf" format="pdf" overwrite="true">
    <span style="font-weight: bold;color:black">#name#</span>#amount# #unit#
</cfdocument>
```

**Comment by r12a** [comment]
Can you provide some screen shots of the outcome, so that it's clear which problem you're encountering? You probably need to directionally isolate the name from the amount, using `<bdi>` or a `dir` attribute on the` span`.

**Comment by behnam** [comment]
Most probably what's happening here is the font file used for the *bold* face does not have the Arabic tables needed for shaping. You need to provide more information, though, to be able to comment further. But, since it's coldfusion that's generating the PDF output, I think there won't be anything related to the standards about it and it's just a system (os/font/rendering software) issue.

**Comment by r12a** [comment]
Seems like this is stale.
