### ISSUE TITLE
[articles/typography/linebreak] Hangul wraps syllables

### ISSUE THREAD

**Issue by NorbertLindenberg** [w3c/i18n-drafts#159]
[source](http://w3c.github.io/i18n-drafts/articles/typography/linebreak.en) [en]

The table in the section Basic Parameters shows Hangul in the "wraps characters" row.

How the English word "character" applies to Hangul isn't really well defined. Hangul has basic components named "jamo", which are combined into syllable blocks. Both jamo and syllable blocks could be called characters, and Unicode encodes both.

Line breaks can occur between words or between syllable blocks. They cannot occur between the jamo that form a syllable block.

I suggest moving the (second) entry for Hangul into the "wraps syllables" row.

Text in the sections "space delimited words", "Sundanese, Cham: space as word separator", and "character-based wrapping" then also needs to be updated.

**Comment by r12a** [comment]
Before making changes i stepped back and re-examined the classification i had been using, and tried some alternatives. The basic table structure remains the same, but i reclassified several things.

I relocated Hangul as syllabic, because indeed, unlike Japanese, hangul non-jamo characters represent syllables, as do the (rare) jamo-based sequences, as you mention. Japanese stays as character-based, but Chinese is a little ambiguous; in the end i relocated Chinese under syllable-based, since the han characters do represent syllables (unlike bopomofo) even if they are different from most of the other syllable-based languages because a syllable is always a single character (which makes the behaviour somewhat like character-based wrapping).

Various parts of the article were rewritten to accomodate changes of this kind.
