### ISSUE TITLE
[questions/qa-bidi-space]  

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-drafts#17]
[source](http://w3c.github.io/i18n-drafts/questions/qa-bidi-space.en.html) [en]

The examples are a little odd. The HTML code sections show "rtl text" and "ltr text", but the illustrations show real text. This leads to some cognitive dissonance when the text refers to the illustration text.

Consider having both the real and explanatory text in the code? For example you could use ruby for the "rtl/ltr text" bits.  It would require some behind the scenes bidi markup of course. But the example code and illustrations would match better. Just a thought..

**Comment by r12a** [comment]
they were originally arabic text in both places, but that's problematic because of the bidirectional nature of the example (not to mention very time consuming to create the example!)  I decided that this way was better, partly because it generalises things beyond arabic, and partly because you don't get distracted by the bidi issues that aren't important.

**Comment by aphillips** [comment]
Sure, but the text doesn't quite make sense as written if the example text doesn't appear in the "code" bits. And this _is_ about bidi fundamentally, no?

Once you're built the example, you'd be in good shape. (I thought the ruby idea was kind of cool... check out http://inter-locale.com/test/bidi-space-article.html)

**Comment by r12a** [comment]
I made changes to the example pattern and to the text around it to make it clearer that the first thing is an example of a pattern, and the second a for-instance.  I also applied the standard UPPERCASE IS RTL and lowercase is ltr to the pattern.  Hopefully, that makes things clearer.
