### ISSUE TITLE
https://www.w3.org/International/articlelist.fr needs update

### ISSUE THREAD

**Issue by brandelune** [w3c/i18n-drafts#206]
The page gives "Types of language declaration" as available for translation but it has been available for a few days already as "Types de déclaration de langues"

**Comment by r12a** [comment]
Not sure whether i fixed it inadvertently, but it seems ok now.
https://www.w3.org/International/articlelist.fr#language

Please reopen this if you still have a problem.

**Comment by brandelune** [comment]
Nice ! Il looks much better !

**Comment by brandelune** [comment]
"Handling character encodings in HTML and CSS" is still displayed as [en] only (it was announced as translated on July 29).

**Comment by r12a** [comment]
Fixed. Thanks for the reminder.

I also changed the translation process, to make things clearer.  https://github.com/w3c/i18n-drafts/projects/2 now has an "Uploaded" column before the newly renamed "Announced" column. This means that we can upload stuff to the server straight away, and group things for announcement, rather than for upload.

**Comment by brandelune** [comment]
By the way, my name is Helary, without acute accent (Hélary) :)

**Comment by r12a** [comment]
Oh, sorry. I wonder where i picked up the accent...  I'll remove it whenever i see it.
