### ISSUE TITLE
[questions/qa-lang-priorities]  Why I've got russian language on this page?

### ISSUE THREAD

**Issue by skywinder** [w3c/i18n-drafts#231]
[source] (https://www.w3.org/International/questions/qa-lang-priorities) [ru]

Hi. Just come to check, why I see Russian web page.
According to this https://validator.w3.org/i18n-checker/check?uri=www.w3.org%2FInternational%2Fquestions%2Fqa-lang-priorities.en#validate-by-uri+

I have these headers: 
``` Accept-Language: en-GB,en-US;q=0.7,ru;q=0.3```

So, looks it should show english by default, so why I'm still see russian locale for the page?

**Comment by r12a** [comment]
hi @skywinder.  Did you perhaps look at the Russian translation before (ie. by following the links at the top right of the page)?  If you did, you'll always be sent Russian translations of those articles until you click on the link to the English version (in the same place).  This is by design, so that people who want to read the pages in a language different from that in their browser settings don't have to keep switching languages. (See https://www.w3.org/International/questions/qa-site-conneg)

If that's not the situation, please let me know.

**Comment by skywinder** [comment]
thank you for the response. I will check it later and repeat test with clear cookies. thanks!
