### ISSUE TITLE
[questions/qa-i18n.ru] Some words and phrases haven't been translated

### ISSUE THREAD

**Issue by corocoto** [w3c/i18n-drafts#245]
[source] (https://www.w3.org/International/questions/qa-i18n.ru#survey) [ru]

This article contains some words and phrases that haven't been translated.
Like: 
 * >предполагаемая аудитория: anyone who is wondering about the comparative meanings of internationalization and localization.
* >Иногда локализация пишется как " "l10n", где 10 - это число букв между буквами 'l' and 'n' в английском варианте слова "localization".

I can trying to help you with it.

**Comment by r12a** [comment]
Thanks @CreativeRusBear.

>  предполагаемая аудитория: anyone who is wondering about the comparative meanings of internationalization and localization.

I dealt with this by removing it, per our more recent template.

>  Иногда локализация пишется как " "l10n", где 10 - это число букв между буквами 'l' and 'n' в английском варианте слова "localization".

Apart from the messy quote marks, i don't think the word 'localization' needs to be translated, since the text is describing an abbreviation of an English word.  It may, however, have been better to explain that this is an abbreviation of 'the English term' (as it does for i18n lower down) – or to simply omit that explanation for the Russian version.

I updated the English original, so that this will become clear if future translators also do literal translations.

**Comment by corocoto** [comment]
@r12a, I didn't mean to translate "localization" word in this context. I wanted to fix this small bit of text: `'l' and 'n'` (also in this context).

>I updated the English original, so that this will become clear if future translators also do literal translations.

O, it's cool!

**Comment by r12a** [comment]
Fixed by the commit above.
