### ISSUE TITLE
[articles/inline-bidi-markup/index]  

### ISSUE THREAD

**Issue by nickshanks** [w3c/i18n-drafts#27]
[source](https://www.w3.org/International/articles/inline-bidi-markup/#override) [en]

The very last section, about the BDO element, gives an example in Hebrew. It would be of use to give an example in Arabic too. I would expect to see the isolate glyphs used in an example such as this, where each memory location is an individual block, but BDO might just present the arabic joined up but the word spelt sdrawkcab (I haven't tested to see). You could also use a monospace font for computer memory. Additionally there is a comma in the example that is not in the presented source code.

**Comment by r12a** [comment]
Thanks for the comment.

Hebrew was chosen for this example precisely because it doesn't have the Arabic joining behaviour. When arabic characters are used they do indeed join, which makes it more difficult for people (esp. non-Arabic readers) to understand what's going on (since the shaping makes it difficult for them to find individual characters).

It may be worth adding a note to say that Arabic text still joins, but is harder to read as a result.

We didn't use a monospaced font in part to keep the example simple. Note however that monospaced fonts don't work well for arabic either – there is a mixture of very narrow and very wide characters, and in addition the ascenders and descenders are much longer than in latin text.

I'll fix the comma issue.

**Comment by r12a** [comment]
added the missing comma at 
https://github.com/w3c/i18n-drafts/commit/d20d1da0b56382db56bd4db83c852bfae74284b1

having heard nothing more about the other topics, i'm closing this.  Reopen if you want to pursue it further.

**Comment by nickshanks** [comment]
At least the issues have been considered. I do agree that a note to say `Arab` text still joins would be beneficial. As I mentioned, I had expected isolate glyphs to be used. So, rather than, say, حَرْف appearing as ﺣَ‎رْ‎ف, as might be interpreted, it would appear as ف​رْ​حَ — you're saying it's neither of these, but فرْحَ instead? It definitely needs some clarification.
