### ISSUE TITLE
[tutorials/tutorial-char-enc/index]  Tag example has closing slash

### ISSUE THREAD

**Issue by RobBelics** [w3c/i18n-drafts#397]
[source] (https://www.w3.org/International/tutorials/tutorial-char-enc/) [en]

While allowed, no HTML specification requires or calls for a closing slash. The <meta> example shows one here. W3C examples don't usually do that.

**Comment by r12a** [comment]
This was a hangover from the time we used to worry more about XML syntax for HTML.  I agree that we probably don't need to do so these days, since the general developer no longer uses it, and those who do will know what to do, so i removed the trailing slash from  the example on this page, and the page it points to (and all the translations).
