### ISSUE TITLE
[questions/qa-bidi-source]  Editorial issue

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-drafts#466]
[source] (https://w3c.github.io/i18n-drafts/questions/qa-bidi-source.en.html) [en]

> If you are creating a large amount of right-to-left text, it makes sense to set the base direction of the editing window in your editor to right-to-left. This helps ensure that the paragraph content and its punctuation is correctly ordered.

Maybe change the second sentence to:

> This helps ensure that the paragraph content and its **punctuations are** correctly ordered.

**Comment by r12a** [comment]
Now reads:

> This helps to ensure that both the paragraph content and its punctuation are correctly ordered.

**Comment by xfq** [comment]
Ah, right. "Punctuation" is uncountable according to https://www.oxfordlearnersdictionaries.com/definition/english/punctuation

We should probably fix the section title in [alreq](https://www.w3.org/International/alreq/#h_character_tables_punctuations_and_symbols).

**Comment by ntounsi** [comment]
Few more comments

[ § Editing markup section](https://w3c.github.io/i18n-drafts/questions/qa-bidi-source.en.html#reasons)

1) After first markup example: "Furthermore, sentence-final punctuation, such as the period here". period or exclamation mark here?

2) Paragraph before next example :  "..._things can get much worse if the overall context for the source code is right-to-left._" Indeed! But I would add as a remark (after the example) that this not very usual since markup languages are generally  in English, so the context in editing a source code is unlikely to be right-to-left.

3) The paragraph before this figure-1: The first sentence "_It is not unknown for authors to edit in LTR mode after applying a directional override to the whole of the source code_." Is not clear to me. Do you mean apply <bdo> markup to the whole code and edit in Wysiwyg mode, or edit in HTML source mode with Bidi disabled ?
Last sentence: "_because the normal joining forms are altered as well as the direction_." Normal joining forms **take place** but backward, altering the readability.

4) Just bellow that, in [figure 1](https://w3c.github.io/i18n-drafts/questions/qa-bidi-source.en.html#fig_joining_forms), I would add a third line example where normal joining forms are not rendered (obtained here by LRO and  ZWNJs where fit):

‭ي‌ح‌ق  ل‌ك‌ل  فرد  أ‌ن  ي‌غادر‬ 

5) Figure caption: should be RTL top and LTR bottom ?

**Comment by r12a** [comment]
Thanks @ntounsi.  I made changes for most of the points you raised.

I didn't mention the isolated forms, because i think that requires even more difficult setup these days, given fallback font capabilities, widespread Arabic system fonts, etc.  I know you do that, but do you know whether many others do?  I did, however, rewrite the relevant paragraph to read:

> It is not a particularly good idea for authors to edit in LTR mode after applying a directional override to the whole of the source code. For this, an editor that knows nothing about the Unicode Bidirectional Algorithm would be necessary, because it avoids the reordering of the text. This makes it easier to understand the mixture of markup and content, but the author has to read all the RTL content backwards. In a cursive script such as Arabic this is particularly problematic, because the normal joining shapes are altered as well as the direction.
