### ISSUE TITLE
Feedback on questions/qa-date-format - Promoting YYYY-0MM-DD

### ISSUE THREAD

**Issue by FBTHFL** [w3c/i18n-drafts#5]
[source](http://www.w3.org/International/questions/qa-date-format) [en]  

YYYY-0MM-DD format would present a date in a way that most could clearly interpret in their country. Using the four digit year, three digit month (zero-filled) and a two digit day has many benefits. That way 1973-004-03 , 004-03-1973 and 03-004-1973 are clearly April 3, 1973  and not March 4, 1973 - in most cultures. This would avoid frustrations and reprocessing time to correct mistakes. More importantly in international research, development, medical records and other business that cross international boundaries; critical errors and misunderstandings would be reduced. Thoughts?

**Comment by r12a** [comment]
Format-wise, it seems as if that may have been a useful approach, although the spare 0 in the month field seems a bit odd. I'm afraid the boat has already sailed however, and moving to that format would require revolutionary change.  I also suspect that ordinary people would tend to omit the leading zeros a lot, in practise, causing a relapse into confusion. For scientific use, as you mention, i suspect that the YYYY-MM-DD format (based on the Gregorian calendar, of course) is unambiguous enough.  I'm not aware that YYYY-DD-MM is used anywhere.

**Comment by arlelommel** [comment]
I've got to agree with Richard. The YYYY-MM-DD format is, in most customer-facing applications, rendered in a locale-specific format anyway, so users who don't understand the date format are usually (although certainly not always) insulated from seeing the raw ISO date format. While the stated goal is to avoid needing to reprocess data, the effect of adding another format now would be to increase reprocessing for the millions of legacy uses that would not recognize the new format. This is always an issue when making changes to established items, but would be particularly problematic for dates because they are so ubiquitous. Since many backbone utilities in corporations and other institutions quietly run and are largely forgotten, trying to update them all would be a Sisyphean task.

And I'm also not aware of anyone using YYYY-DD-MM. There are many locale-specific instances of DD-MM-YYYY (German, for instance) and MM-DD-YYYY (English) and even YYYY-MM-DD (Hungarian), but I've never seen the date format that creates the confusion here (which isn't to say it doesn't exist, just that I've never run across it).

**Comment by dyacob** [comment]
My only thought is that if a new symbol is introduced to disambiguate the month field, why not a literal "M"?  For example:  1973-M04-03  .  Its less jarring to me than the "0", "M" for "Month" is English biased though (more radically, a calendar emoji could be used for the field, but I assume 7-bit text remains a constraint).

**Comment by duerst** [comment]
I think "revolutionary change" goes a bit too far. But I agree it would need a large uphill battle to try to popularize a YYYY-0MM-DD format. YYYY-MM-DD works because nobody is using YYYY-DD-MM. What works even better user-facing is to use month names (and of course four-digit years).

**Comment by r12a** [comment]
Closing since discussion seems to have run its course.
