### ISSUE TITLE
questions/qa-bidi-unicode-controls: bidi marks are not control characters

### ISSUE THREAD

**Issue by 3052** [w3c/i18n-drafts#556]
this page:

https://w3.org/International/questions/qa-bidi-unicode-controls

sourced here:

https://github.com/w3c/i18n-drafts/blob/gh-pages/questions/qa-bidi-unicode-controls.en.html

contains:

~~~
Unicode provides two other invisible directional control characters.
Character 	Name 	Code point 	Equivalent markup 	Comment
LRM 	LEFT-TO-RIGHT MARK 	U+200E 	none 	strongly typed LTR character
RLM 	RIGHT-TO-LEFT MARK 	U+200F 	none 	strongly typed RTL character
~~~

but these aren't control characters. according to the same website in multiple locations, they are "General Punctuation":

- https://w3.org/International/Spread/punctuation.txt
- https://w3.org/TR/WD-html40-970708/sgml/entities.html

**Comment by xfq** [comment]
These characters are not punctuation, they're just in the "General Punctuation" block. General Punctuation is a Unicode block containing punctuation, spacing, and formatting characters.

> Unicode provides two other invisible directional control characters.

They are "directional control" characters, instead of directional "control characters".

Since [Unicode](https://www.unicode.org/charts/PDF/U2000.pdf) calls them "format characters", we can change the text to something like:

> Unicode provides two other invisible format characters related to direction.

**Comment by 3052** [comment]
> Unicode provides two other invisible format characters related to direction.

thats an improvement, so sounds good
