### ISSUE TITLE
Cultural norms & expectations

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-drafts#560]
https://www.w3.org/International/i18n-drafts/nav/about#culture

This section talks about symbolism, colours, layout, information structures, monetization, and legal considerations.

In addition to the things above, I think we can mention other things like local jargon. For example "9 to 5" does not work for all countries and regions, because they have different concepts of how long a work day is.

**Comment by xfq** [comment]
There didn't seem to be enough interest. Closing.

**Comment by aphillips** [comment]
??

I'm not opposed to closing this issue, but would note that I'm not sure where you expected interest to come from... if not from yourself or from our recruiting WG members to do some writing 😉

I think it's okay to have issues like this stashed away "for a rainy day" (to use an English idiom), i.e. for when we have time or are working on a specific document revision in the future.

**Comment by ntounsi** [comment]
At the same time, we could fix some typos that I noted some time ago in the example in [Fig.1](https://www.w3.org/International/i18n-drafts/nav/about#fig_arabic) .

I think the example in Arabic. The right text would be :

 ‫لحجز مواعيد اللقاح ضد COVID-19 انتقل إلى،
www .nhs.uk/covid-vaccination أو اتصل
برقم 119 الذي. ‬ 

that is :
- First word,  **ج** instead of **خ**
- Second word, no space inside (after Waw **و** I think)
- The linebreak at the end of second line is inside a word. Must be a whole word **برقم** and begin with **ب** not **ي**.

For your convenience, here it is an attempt with image :
![i18nArabicImage](https://github.com/w3c/i18n-drafts/assets/15004708/b848e559-2cfc-4e14-a5eb-ae5b0a248a7a)

This is not important, and it doesn't affect the purpose of the example, but since the article is a presentation of the I18n activity, it might as well be right. ;-)
