### ISSUE TITLE
[articles/definitions-time/index]  

### ISSUE THREAD

**Issue by dehildum** [w3c/i18n-drafts#57]
[source](http://w3c.github.io/i18n-drafts/articles/definitions-time/index.en.html) [en]

The document would be improved by using the terminology and glossary of ISO 8601. As written it uses ambiguous, colloquial terminology that is somewhat misleading and does not correspond to current usage. 

It should also call out lessor known issues with current practice, such as the assumption that there are 60 seconds in a minute; in fact for precise time keeping, some minutes have 61 seconds just as some Februarys have 29 days. Systems that do not allow for this are broken by design.

Finally, it is not correct that the differences between GMT and UTC do not affect average users. Many systems in use every day would be critically affected by the difference if it were not handled correctly. Further, the Unix millisecond standard is already having issues, with modern file systems tracking modification times to nanosecond to allow for proper synchronization.

**Comment by r12a** [comment]
@dehildum thanks for the comments, but can you be a little more specific?  Which aspects of the terminology do think need to be changed?

Certainly, the man in the street is affected by leap seconds and the differences between GMT and UTC, but at the level at which this article is pitched, this is considered to be unnecessary detail.  For more information on that, see [Working with Time Zones](https://www.w3.org/TR/timezone/), which is linked to at the top of the article.  I'll reword the text slightly in that respect.

**Comment by dehildum** [comment]
I think your readers would be a bit better served if you discuss time using a time line and explain instances and durations - the interval between instances.

Then you can talk measuring time via calendars - this allows you to more naturally introduce the Unix and other methods of handling time as additional calendars, and makes the concept of time zones a bit easier, as they are part of calendars. You can then go to local time, and skip the Wall Clock time terminology, instead presenting local time as "wall clock time", lower case. You can also skip field based time - again a concept not really used anywhere in common or professional usage. The discussion of calendars should take place at the top of the article, not at the bottom, and you should include more than one human calendar - I suggest the Japanese imperial era calendar.

Floating times can be handled as I discussed in my previous feedback. You really do need a more international example than the Queen’s birthday.

Regards,
Eric

**Comment by r12a** [comment]
The introduction was changed to more clearly state that this article intends to explain terminology in a simple way, and that readers should go to [Working with Time Zones](https://www.w3.org/TR/timezone/) for a more detailed approach. I think many of the above suggestions are more relevant to that article.

I changed "but none that affect the average person" to "but none that the average person would notice".

Field-based time is very common in Web standards. 'Wall clock time' _is_ in lower case - it's just at the start of a sentence, and it's a term i hear used often, ergo it's inclusion here.  The article says "There are numerous other calendars in use around the world" but leaves a discussion of those to the more detailed source (such as the one just mentioned).  I didn't choose the Queen's birthday as an attempt to find an international example - i chose it because the preparations were happening around me (in the UK) as i wrote, and it related to the earlier examples of time formats.
