### ISSUE TITLE
[articles/typography/justification]  Advice for implementers/authors section

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-drafts#77]
[source] (http://w3c.github.io/i18n-drafts/articles/typography/justification.en.html) [en]

I find this whole section a little dubious. It seems to start from the assumption that language tags are a prime factor in choosing a justification strategy, and that an absence of language metadata will cause justification to fail. There may certainly be line-break rules that are modified by language, particularly in the case of ideographic-based text, but i don't think it's clear what parameters of justification are affected by a knowledge of the language, much less the need for a script subtag. The second subsection starts out talking about how to handle untagged text, but the bullet points rely on language knowledge for application of the different approaches outlined.

It would also be good to clearly signpost which advice is relevant to authors vs implementers.

**Comment by asmusf** [comment]
There's nothing dubious about it.

While it's possible that many scripts/languages may more or less happily work with one or the other standard justification strategies, there are definitely some differences in preference. Many of them can be observed in (printed) newspapers because those typically have narrow, justified columns of text.

The article mentions the difference in treatment of compression for Japanese and Chinese.

Even for the Latin script, there are differences. Readers of English seem to be highly tolerant of large interword or intercharacter spaces when text is justified in narrow columns. (See newsprint).

In German, e x p a n d e d  text used to be a common form of emphasis. As a result, expansion of intercharacter spaces is highly undesirable. (If allowed at all, then with much smaller maximum value).

With long compound words common, hyphenation is the method of choice; in contrast to English-language publications, where hyphenation almost appears to be frowned upon.

If your goal is to select "best default layout for text justified in narrow columns" then the preferred strategies very clearly differ by script and writing system (even if many languages may share similar behaviors).

The problem here is that markup or APIs divide the task of justification across a number of discrete choices implemented by different subsystems. For good typography, it's not just justify on/off but, also hyphenation on/off or compress punctuation on/off.

**Comment by r12a** [comment]
I made edits following discussion with Fantasai, who plans to move some of the content elsewhere, and i included the German example.
