### ISSUE TITLE
[questions/qa-forms-utf-8]  

### ISSUE THREAD

**Issue by bkdotcom** [w3c/i18n-drafts#90]
[source] (https://www.w3.org/International/questions/qa-forms-utf-8) [en]

https://en.wikipedia.org/wiki/UTF-8

> (UTF-8) was designed for backward compatibility with ASCII

> The first 128 characters of Unicode, which correspond one-to-one with ASCII, are encoded using a single octet with the same binary value as ASCII, so that valid ASCII text is valid UTF-8-encoded Unicode as well

your regex:  `[\x09\x0A\x0D\x20-\x7E]            # ASCII`  
should simply be:  `[\x00-\x7F]            # ASCII`

About as official as it gets:
http://www.unicode.org/Public/8.0.0/charts/CodeCharts.pdf

**Comment by vishnukanduri** [comment]
Perfectly and excellently explained.

-----Thank You W3C

**Comment by r12a** [comment]
@duerst do you want to make this change?

**Comment by duerst** [comment]
Either way would be fine. If we make the change, then I think it would be good to add something like the following at the end:
"The above regular expression can be tailored by adding application-related restrictions. As an example, many control characters can be excluded by replacing [\x00-\x7F] with [\x09\x0A\x0D\x20-\x7E]."

While we are at it, can we also make the following changes:
"m/\A(" -> "/\A(" (That makes the example a bit more general because slashes are delimiters for regular expressions in quite a few programming languages, but the initial 'm' is very Perl-specific.)
"but your users may type in other characters" -> "but your users may type in such characters"

**Comment by r12a** [comment]
I created a PR at https://github.com/w3c/i18n-drafts/pull/260.  @duerst could you check it for me.  If it's ok, i'll publish it and add the changes to all the (many) translations.

**Comment by duerst** [comment]
@r12a: The PR looks good to mee!

**Comment by r12a** [comment]
Merged.

**Comment by r12a** [comment]
Changes propagated to translations at https://github.com/w3c/i18n-drafts/commit/b976066c9bf7786f7cfbdeb772f6e9abf3410934
