### ISSUE TITLE
[articles/ruby/markup]  link issues

### ISSUE THREAD

**Issue by mwil** [w3c/i18n-drafts#94]
[source] (https://w3c.github.io/i18n-drafts/articles/ruby/markup.en) [en]

Ruby styling link is the above document is 404 (direct link: [styling](https://w3c.github.io/i18n-drafts/articles/ruby/styling))

**Comment by r12a** [comment]
Should now be fixed by https://github.com/w3c/i18n-drafts/commit/ed1d815c3bb6dbb8ab2eebe2fa779b8c51fc515c

Actually this is no longer the canonical version, since the article was publishing. You can find that version (where the links actually work) at https://www.w3.org/International/articles/ruby/markup

I'll give myself an action to add some scripting to pages like this to indicate where to read the canonical version, if one exists.

Thanks for the comment.
